### ISSUE TITLE
[panic]  on `arabica-6`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1776]
```
2023-02-17T20:39:32.311+0100    INFO    das     das/store.go:59 stored checkpoint to disk: SampleFrom: 1390, NetworkHead: 1389, Workers: 14
2023-02-17T20:39:46.710+0100    DEBUG   shrex/peer-manager      peers/manager.go:285    got hash from shrex-sub {"peer": "12D3KooWDgG69kXfmSiHjUErN2ahpUC1SXpSfB2urrqMZ6aWC8NS", "datahash": "0659721A81DF2FBFBF80179E6D789541C95820E912F4907D1A53DECA971725AE"}
2023-02-17T20:39:46.740+0100    DEBUG   shrex/peer-manager      peers/manager.go:285    got hash from shrex-sub {"peer": "12D3KooWDgG69kXfmSiHjUErN2ahpUC1SXpSfB2urrqMZ6aWC8NS", "datahash": "257760461993F8F197B421EC7435F3C36C3734923E3DA9A42DC73B05F07B3D08"}
2023-02-17T20:39:46.740+0100    WARN    header/sync     sync/sync_head.go:164   received known network header   {"current_height": 1389, "header_height": 1388, "header_hash": "8745C27804DAEC83AEA649C5C537AA36EF6841E852395A0A8119ABFF293A7F57"}
2023-02-17T20:39:54.259+0100    DEBUG   shrex/peer-manager      peers/manager.go:285    got hash from shrex-sub {"peer": "12D3KooWAYeSWYZZHpU7JQq4tW9Pvco8jce9xNyaYGoAJCgkH3fX", "datahash": "42049621FEC82E10C455FDD733E342745C41290F9FC2CBF253D8803F1981D6C1"}
2023-02-17T20:39:54.269+0100    INFO    header/sync     sync/sync_head.go:151   new network head        {"height": 1392, "hash": "73709019F6E1CB846FF35FFBD52AE8FCD36C28717C0FAA43A7ABE12E0875A21E"}
2023-02-17T20:39:54.270+0100    INFO    das     das/subscriber.go:34    new header received via subscription    {"height": 1392}
2023-02-17T20:39:54.270+0100    DEBUG   das     das/state.go:90 updated head    {"from_height": 1392, "to_height": 1392}
2023-02-17T20:39:54.271+0100    DEBUG   das     das/worker.go:50        start sampling worker   {"from": 1390, "to": 1392}
2023-02-17T20:39:54.271+0100    DEBUG   das     das/worker.go:50        start sampling worker   {"from": 1392, "to": 1392}
2023-02-17T20:39:54.288+0100    DEBUG   shrex/peer-manager      peers/manager.go:285    got hash from shrex-sub {"peer": "12D3KooWAYeSWYZZHpU7JQq4tW9Pvco8jce9xNyaYGoAJCgkH3fX", "datahash": "257760461993F8F197B421EC7435F3C36C3734923E3DA9A42DC73B05F07B3D08"}
2023-02-17T20:39:54.291+0100    WARN    header/sync     sync/sync_head.go:164   received known network header   {"current_height": 1392, "header_height": 1390, "header_hash": "C9F328F0B1AA5377DEE66B2F43FED8BC8475B49472C17219F9254EE6278C0902"}
2023-02-17T20:40:07.331+0100    DEBUG   shrex/peer-manager      peers/manager.go:285    got hash from shrex-sub {"peer": "12D3KooWDgG69kXfmSiHjUErN2ahpUC1SXpSfB2urrqMZ6aWC8NS", "datahash": "42049621FEC82E10C455FDD733E342745C41290F9FC2CBF253D8803F1981D6C1"}
panic: putting the same entry twice not supported

goroutine 673 [running]:
github.com/libp2p/go-libp2p-pubsub/timecache.FirstSeenCache.Add({0x14009989a10?, 0x14009989a40?, 0x140094c88c0?, 0x140096ecf48?}, {0x140030b3920, 0x20})
        /Users/rford/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/timecache/first_seen_cache.go:32 +0x264
github.com/libp2p/go-libp2p-pubsub.(*PubSub).markSeen(0x140097f0d80, {0x140030b3920, 0x20})
        /Users/rford/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/pubsub.go:1002 +0x128
github.com/libp2p/go-libp2p-pubsub.(*validation).validate(0x140097d0c40, {0x1400af9c060, 0x1, 0x0?}, {0x1400c454330, 0x26}, 0x14003042800, 0x0)
        /Users/rford/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/validation.go:288 +0xf4
github.com/libp2p/go-libp2p-pubsub.(*validation).validateWorker(0x140097d0c40)
        /Users/rford/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/validation.go:266 +0x4c
created by github.com/libp2p/go-libp2p-pubsub.(*validation).Start
        /Users/rford/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/validation.go:133 +0x6c
```

**Comment by renaynay** [comment]
https://github.com/libp2p/go-libp2p-pubsub/issues/521
