### ISSUE TITLE
bug(share/retriever): panic: pushed data has to be lexicographically ordered by namespace IDs

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1891]
Found while testing 5 full nodes syncing IPLD only against 1 bridge in **swamp**

```
2023-03-10T18:48:01.262+0100	INFO	header/sync	sync/sync_head.go:161	new network head	{"height": 497, "hash": "342358D4189FA5FB6666484E3D598AB3B0543AF73B23AD979E127D478020D37E"}
panic: pushed data has to be lexicographically ordered by namespace IDs: last namespace: f1527a61edb7a3b6, pushed: 13ef3b104d974896

goroutine 289781 [running]:
github.com/celestiaorg/celestia-app/pkg/wrapper.(*ErasuredNamespacedMerkleTree).Push(0x1406a363200, {0x1404fc0e400, 0x200, 0x200})
	/Users/rene/go/pkg/mod/github.com/celestiaorg/celestia-app@v0.12.0-rc7.0.20230310141934-734b05421415/pkg/wrapper/nmt_wrapper.go:96 +0x170
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).computeSharesRoot(0x100?, {0x1407c530000, 0x100, 0x1407c530000?}, 0x1?, 0x1407c530000?)
	/Users/rene/go/pkg/mod/github.com/celestiaorg/rsmt2d@v0.8.0/extendeddatacrossword.go:377 +0xa8
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).verifyAgainstRowRoots(0x140c0259960?, {0x14036d15000, 0x100, 0x100?}, 0x46, {0x1407c530000?, 0x0?, 0x0?})
	/Users/rene/go/pkg/mod/github.com/celestiaorg/rsmt2d@v0.8.0/extendeddatacrossword.go:279 +0x44
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrosswordRow(0x140c0259960, 0x46, {0x14036d15000, 0x100, 0x100}, {0x14036d16800, 0x100, 0x100})
	/Users/rene/go/pkg/mod/github.com/celestiaorg/rsmt2d@v0.8.0/extendeddatacrossword.go:143 +0x23c
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrossword(0x140c0259960, {0x14036d15000, 0x100, 0x100}, {0x14036d16800, 0x100, 0x100})
	/Users/rene/go/pkg/mod/github.com/celestiaorg/rsmt2d@v0.8.0/extendeddatacrossword.go:86 +0xd4
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).Repair(0x1400062c100?, {0x14036d15000, 0x100, 0x100}, {0x14036d16800, 0x100, 0x100})
	/Users/rene/go/pkg/mod/github.com/celestiaorg/rsmt2d@v0.8.0/extendeddatacrossword.go:69 +0x68
github.com/celestiaorg/celestia-node/share/eds.(*retrievalSession).Reconstruct(0x1408e408750, {0x1061e9f68, 0x140624f7290})
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/eds/retriever.go:173 +0x148
github.com/celestiaorg/celestia-node/share/eds.(*Retriever).Retrieve(0x14024bed100, {0x1061e9f68?, 0x140624f7230?}, 0x140368889b0)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/eds/retriever.go:83 +0x5d0
github.com/celestiaorg/celestia-node/share/getters.(*IPLDGetter).GetEDS(0x14024ba7698, {0x1061e9ec0, 0x140144f7cc0}, 0x104bb4e94?)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/getters/ipld.go:73 +0x208
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS.func1({0x1061e9ec0?, 0x140144f7cc0?}, {0x1061d24c0?, 0x14024ba7698?})
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/getters/cascade.go:59 +0x44
github.com/celestiaorg/celestia-node/share/getters.cascadeGetters[...]({0x1061e9f68, 0x140624f7080}, {0x14024bcdce0, 0x2, 0x14018318720}, 0x1409f3135c8?)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/getters/cascade.go:123 +0x4b0
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetEDS(0x14024ba76e0, {0x1061e9f68, 0x140624f7050}, 0x140368889b0)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/getters/cascade.go:62 +0x228
github.com/celestiaorg/celestia-node/share/getters.(*TeeGetter).GetEDS(0x14024ba76f8, {0x1061e9f30, 0x14017a3a360}, 0x14036d55420?)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/getters/tee.go:58 +0x218
github.com/celestiaorg/celestia-node/share/availability/full.(*ShareAvailability).SharesAvailable(0x14025978e40, {0x1061e9f30, 0x14017a3a360}, 0xc0faf96158c59938?)
	/Users/rene/go/src/github.com/renaynay/celestia-node/share/availability/full/availability.go:69 +0xa0
github.com/celestiaorg/celestia-node/das.(*DASer).sample(0x140259728f0, {0x1061e9f30, 0x14017a3a360}, 0x14036896900)
	/Users/rene/go/src/github.com/renaynay/celestia-node/das/daser.go:149 +0x48
github.com/celestiaorg/celestia-node/das.(*worker).sample(0x1402d8e2f30, {0x1061e9ec0, 0x140364ece00}, 0x1400009a2b0?, 0x0?)
	/Users/rene/go/src/github.com/renaynay/celestia-node/das/worker.go:107 +0x94
github.com/celestiaorg/celestia-node/das.(*worker).run(0x1402d8e2f30, {0x1061e9ec0, 0x140364ece00}, 0x102fac9d8?, 0x14024bfe3c0)
	/Users/rene/go/src/github.com/renaynay/celestia-node/das/worker.go:71 +0x144
github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker.func1()
	/Users/rene/go/src/github.com/renaynay/celestia-node/das/coordinator.go:109 +0x68
created by github.com/celestiaorg/celestia-node/das.(*samplingCoordinator).runWorker
	/Users/rene/go/src/github.com/renaynay/celestia-node/das/coordinator.go:107 +0x28c
```

**Comment by renaynay** [comment]
Closing as stale, have not seen this again.
