### ISSUE TITLE
`celestia rpc state BalanceForAddress <address>` errors

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2092]
### Celestia Node version

v0.9.1

### OS

macOS

### Steps to reproduce it

1. set your auth token
2. try the following commands

```bash
# in
celestia rpc state BalanceForAddress celestia1qs2qvwfvdynkc7dq7u63d22w5xvac2lys90rl6

# out
{"jsonrpc":"2.0","id":1,"error":{"code":-32700,"message":"unmarshaling params for 'state.BalanceForAddress' (param: *types.Address): json: cannot unmarshal string into Go value of type types.Address"}}
```

```bash
# in
celestia rpc state BalanceForAddress "celestia1qvt2khht6kl5dla9wll82av9nne4904tq5urr9"

# out
{"jsonrpc":"2.0","id":1,"error":{"code":-32700,"message":"unmarshaling params for 'state.BalanceForAddress' (param: *types.Address): json: cannot unmarshal string into Go value of type types.Address"}}
```

```bash
# in
celestia rpc state BalanceForAddress '"celestia1qs2qvwfvdynkc7dq7u63d22w5xvac2lys90rl6"'

# out 
panic: error parsing address: address must be a valid account or validator address

goroutine 1 [running]:
main.parseParams({0x16bd237fb, 0x11}, {0x14001bea4a0, 0x1, 0x0?})
	/Users/joshcs/celestia-node/cmd/celestia/rpc.go:148 +0x1280
main.glob..func5(0x1085306c0?, {0x14001bea480?, 0x3?, 0x3?})
	/Users/joshcs/celestia-node/cmd/celestia/rpc.go:83 +0x70
github.com/spf13/cobra.(*Command).execute(0x1085306c0, {0x14001bea3f0, 0x3, 0x3})
	/Users/joshcs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x1085303e0)
	/Users/joshcs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/joshcs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/joshcs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.run()
	/Users/joshcs/celestia-node/cmd/celestia/main.go:28 +0x58
main.main()
	/Users/joshcs/celestia-node/cmd/celestia/main.go:21 +0x1c
```

```bash
# in, converted to base64
celestia rpc state BalanceForAddress Y2VsZXN0aWExcXMycXZ3ZnZkeW5rYzdkcTd1NjNkMjJ3NXh2YWMybHlzOTBybDY=

# out, truncated for brevity
panic: error parsing address: address must be a valid account or validator address
```

```bash
# in, converted to base64 and in quotes
celestia rpc state BalanceForAddress "Y2VsZXN0aWExcXMycXZ3ZnZkeW5rYzdkcTd1NjNkMjJ3NXh2YWMybHlzOTBybDY="

# out, truncated
panic: error parsing address: address must be a valid account or validator address
```

### Expected result

balance of account

### Actual result

above

**Comment by jcstein** [comment]
this is working on main btw at b222475b1d707e8c4e4cef9b67a5e47348c90bea
