### ISSUE TITLE
share: DagStore panics inside of `eds.Store`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2123]
### Celestia Node version

0.9.0

### OS

linux

### Steps to reproduce it

The synced bootstrappers was restarted and it happenedwere

### Expected result

Working node

### Actual result

Panic

### Relevant log output

```Shell
fatal error: concurrent map read and map write

goroutine 437 [running]:
github.com/filecoin-project/dagstore.(*DAGStore).AcquireShard(0xc02b6dc420, {0x35e8b18?, 0xc00005a038}, {{0xc03cead480?, 0x3ce98e10?}}, 0xc03ceb9aa0, {})
	/go/pkg/mod/github.com/celestiaorg/dagstore@v0.0.0-20230413141458-735ab09a15d6/dagstore.go:437 +0x78
github.com/celestiaorg/celestia-node/share/eds.(*Store).getAccessor(0xc000513f10, {0x35e8b18, 0xc00005a038}, {{0xc03cead480?, 0x10?}})
	/src/share/eds/store.go:286 +0x9b
github.com/celestiaorg/celestia-node/share/eds.(*Store).getCachedAccessor(0xc000513f10, {0x35e8b18, 0xc00005a038}, {{0xc03cead480?, 0x34?}})
	/src/share/eds/store.go:319 +0x27d
github.com/celestiaorg/celestia-node/share/eds.(*blockstore).getReadOnlyBlockstore(0xc02b801fd0, {0x35e8b18, 0xc00005a038}, {{0xc03cf58780?, 0x25f87c0?}})
	/src/share/eds/blockstore.go:124 +0x17f
github.com/celestiaorg/celestia-node/share/eds.(*blockstore).GetSize(0xc02dbb16e0?, {0x35e8b18, 0xc00005a038}, {{0xc03cf58780?, 0xc02ec0c5e0?}})
	/src/share/eds/blockstore.go:67 +0x3f
github.com/ipfs/go-ipfs-blockstore.(*arccache).GetSize(0xc02dbb16e0, {0x35e8b18, 0xc00005a038}, {{0xc03cf58780?, 0xffffffffffffffff?}})
	/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.2.0/arc_cache.go:162 +0x204
github.com/ipfs/go-libipfs/bitswap/server/internal/decision.(*blockstoreManager).getBlockSizes.func1({{0xc03cf58780?, 0xc01f46e200?}})
	/go/pkg/mod/github.com/ipfs/go-libipfs@v0.6.0/bitswap/server/internal/decision/blockstoremanager.go:95 +0x73
github.com/ipfs/go-libipfs/bitswap/server/internal/decision.(*blockstoreManager).jobPerKey.func1()
	/go/pkg/mod/github.com/ipfs/go-libipfs@v0.6.0/bitswap/server/internal/decision/blockstoremanager.go:139 +0x2e
github.com/ipfs/go-libipfs/bitswap/server/internal/decision.(*blockstoreManager).worker(0xc0004b1570)
	/go/pkg/mod/github.com/ipfs/go-libipfs@v0.6.0/bitswap/server/internal/decision/blockstoremanager.go:69 +0xb3
created by github.com/ipfs/go-libipfs/bitswap/server/internal/decision.(*blockstoreManager).start
	/go/pkg/mod/github.com/ipfs/go-libipfs@v0.6.0/bitswap/server/internal/decision/blockstoremanager.go:49 +0x36
```

**Comment by Wondertan** [comment]
Ok, only DAGStore's Start [access the map ](https://github.com/celestiaorg/dagstore/blob/master/dagstore.go#L274)without synchronization. It kinda makes sense because they don't expect anyone to access the dag store until it's started.

However, in our case, it's possible that Bootstrapper during node start receives Bitswap requests accessing the map, and the panic happens. 

The solution here is to block all access to the eds.Store until it's started, or upstream a fix that protects reads during Start.

**Comment by Wondertan** [comment]
Alternatively, we contribute to Bitswap by introducing the Start method on it, so its server only starts when we call the Start instead of auto-start in the constructor. This way Bitswap will be started only after the Dagstore, so this issue would never happen

**Comment by distractedm1nd** [comment]
We fixed this by wrapping the dagstore startup with a lock.
