### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2244]
### Celestia Node version

v0.10.0

### OS

ubuntu

### Install tools

https://docs.celestia.org/pr-preview/pr-753/developers/optimism/

### Steps to reproduce it

https://docs.celestia.org/pr-preview/pr-753/developers/optimism/

### Expected result

no panic

### Actual result

```bash
[36mcelestia-light-node |[0m 2023/05/22 23:17:57 http: panic serving 192.168.32.5:34624: runtime error: invalid memory address or nil pointer dereference
[36mcelestia-light-node |[0m goroutine 72633 [running]:
[36mcelestia-light-node |[0m net/http.(*conn).serve.func1()
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:1854 +0xbf
[36mcelestia-light-node |[0m panic({0x2544a40, 0x4c1e190})
[36mcelestia-light-node |[0m 	/usr/local/go/src/runtime/panic.go:890 +0x263
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/header.(*ExtendedHeader).Height(...)
[36mcelestia-light-node |[0m 	/src/header/header.go:60
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/nodebuilder/header.(*Service).GetByHeight(0xc0188da7c0, {0x3718290, 0xc019730b10}, 0x86959)
[36mcelestia-light-node |[0m 	/src/nodebuilder/header/service.go:57 +0x4b
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.(*Handler).getShares(0xc0188dba00, {0x3718290, 0xc019730b10}, 0x86959, {0xc002066690, 0x8, 0x10})
[36mcelestia-light-node |[0m 	/src/api/gateway/share.go:115 +0xb8
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.(*Handler).handleDataByNamespaceRequest(0x100?, {0x37153a0, 0xc0183dcfc0}, 0xc00e910500)
[36mcelestia-light-node |[0m 	/src/api/gateway/share.go:72 +0x9a
[36mcelestia-light-node |[0m net/http.HandlerFunc.ServeHTTP(0x37182c8?, {0x37153a0?, 0xc0183dcfc0?}, 0x419690?)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.wrapRequestContext.func1({0x37153a0, 0xc0183dcfc0}, 0xc00e910400)
[36mcelestia-light-node |[0m 	/src/api/gateway/middleware.go:51 +0x164
[36mcelestia-light-node |[0m net/http.HandlerFunc.ServeHTTP(0xc017784180?, {0x37153a0?, 0xc0183dcfc0?}, 0x454c16?)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.checkPostDisabled.func1.1({0x37153a0?, 0xc0183dcfc0?}, 0xc017784180?)
[36mcelestia-light-node |[0m 	/src/api/gateway/middleware.go:40 +0x128
[36mcelestia-light-node |[0m net/http.HandlerFunc.ServeHTTP(0xc018f6b4f0?, {0x37153a0?, 0xc0183dcfc0?}, 0xc?)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.setContentType.func1({0x37153a0, 0xc0183dcfc0}, 0xc018f6b4f0?)
[36mcelestia-light-node |[0m 	/src/api/gateway/middleware.go:27 +0x128
[36mcelestia-light-node |[0m net/http.HandlerFunc.ServeHTTP(0x0?, {0x37153a0?, 0xc0183dcfc0?}, 0xc?)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.setContentType.func1({0x37153a0, 0xc0183dcfc0}, 0xc019730ae0?)
[36mcelestia-light-node |[0m 	/src/api/gateway/middleware.go:27 +0x128
[36mcelestia-light-node |[0m net/http.HandlerFunc.ServeHTTP(0xc00e910300?, {0x37153a0?, 0xc0183dcfc0?}, 0x1?)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2122 +0x2f
[36mcelestia-light-node |[0m github.com/gorilla/mux.(*Router).ServeHTTP(0xc008e05c80, {0x37153a0, 0xc0183dcfc0}, 0xc00e910200)
[36mcelestia-light-node |[0m 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
[36mcelestia-light-node |[0m github.com/celestiaorg/celestia-node/api/gateway.(*Server).ServeHTTP(0x0?, {0x37153a0?, 0xc0183dcfc0?}, 0x47188e?)
[36mcelestia-light-node |[0m 	/src/api/gateway/server.go:90 +0x27
[36mcelestia-light-node |[0m net/http.serverHandler.ServeHTTP({0xc01e2d9dd0?}, {0x37153a0, 0xc0183dcfc0}, 0xc00e910200)
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:2936 +0x316
[36mcelestia-light-node |[0m net/http.(*conn).serve(0xc01e2ea240, {0x37182c8, 0xc001fdba70})
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:1995 +0x612
[36mcelestia-light-node |[0m created by net/http.(*Server).Serve
[36mcelestia-light-node |[0m 	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

### Relevant log output

```Shell
https://github.com/jcstein/logs/blob/main/v0.10.0-logs.log
```

**Comment by Wondertan** [comment]
Thanks for reporting @jcstein. The panic looks pretty harsh yet should be fun to debug
