### ISSUE TITLE
on start: `panic: malformed hash: invalid namespaced hash length, got: 48, want: 90, codec:`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2282]
### Celestia Node version

v0.11.0-rc0

### OS

ubuntu and macos

### Install tools

https://docs.celestia.org/nodes/celestia-node/

### Steps to reproduce it

https://docs.celestia.org/nodes/celestia-node/

```bash
# init
celestia light init --p2p.network arabica
```

```bash
# start
celestia light start --core.ip https://rpc-arabica-8.consensus.celestia-arabica.com/ --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network arabica
```

### Expected result

node starts

### Actual result

```log
panic: malformed hash: invalid namespaced hash length, got: 48, want: 90, codec:

goroutine 464 [running]:
github.com/celestiaorg/celestia-node/share/ipld.MustCidFromNamespacedSha256({0x1400317e4b0?, 0x0?, 0x0?})
	/Users/joshstein/celestia-node/share/ipld/nmt.go:159 +0xac
github.com/celestiaorg/celestia-node/share/ipld.Translate(0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/ipld/nmt.go:175 +0xac
github.com/celestiaorg/celestia-node/share/getters.(*IPLDGetter).GetShare(0x140007427c8, {0x105a45e60, 0x14008994230}, 0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/getters/ipld.go:54 +0x424
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetShare.func1({0x105a45e60?, 0x14008994230?}, {0x105a2f600?, 0x140007427c8?})
	/Users/joshstein/celestia-node/share/getters/cascade.go:45 +0x4c
github.com/celestiaorg/celestia-node/share/getters.cascadeGetters[...]({0x105a45f08, 0x1400253fad0}, {0x14001c4eae0, 0x2, 0x14001157750}, 0x14002575bd0?)
	/Users/joshstein/celestia-node/share/getters/cascade.go:123 +0x574
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetShare(0x14000742810, {0x105a45f08, 0x1400253fa40}, 0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/getters/cascade.go:48 +0x42c
github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).SharesAvailable.func1({0x14000763070?, 0x14008993fb0?})
	/Users/joshstein/celestia-node/share/availability/light/availability.go:65 +0x168
created by github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).SharesAvailable
	/Users/joshstein/celestia-node/share/availability/light/availability.go:63 +0x29c
```

#### Init

```Shell
celestia light init --p2p.network arabica
2023-05-30T16:36:12.767-0400	INFO	node	nodebuilder/init.go:28	Initializing Light Node Store over '/Users/joshstein/.celestia-light-arabica-6'
2023-05-30T16:36:12.767-0400	INFO	node	nodebuilder/init.go:60	Saved config	{"path": "/Users/joshstein/.celestia-light-arabica-6/config.toml"}
2023-05-30T16:36:12.767-0400	INFO	node	nodebuilder/init.go:62	Accessing keyring...
2023-05-30T16:36:12.769-0400	WARN	node	nodebuilder/init.go:191	Detected plaintext keyring backend. For elevated security properties, consider using the `file` keyring backend.
2023-05-30T16:36:12.770-0400	INFO	node	nodebuilder/init.go:206	NO KEY FOUND IN STORE, GENERATING NEW KEY...	{"path": "/Users/joshstein/.celestia-light-arabica-6/keys"}
2023-05-30T16:36:12.782-0400	INFO	node	nodebuilder/init.go:211	NEW KEY GENERATED...

NAME: my_celes_key
ADDRESS: celestia17ktvf3zm2q8p970ghs9fqy4dtymcedyvgq4mhy
MNEMONIC (save this somewhere safe!!!):
[redacted]

2023-05-30T16:36:12.782-0400	INFO	node	nodebuilder/init.go:69	Node Store initialized
```

#### Start

```Shell
2023-05-30T16:36:17.721-0400	INFO	node	nodebuilder/module.go:23	Accessing keyring...
2023-05-30T16:36:17.725-0400	INFO	module/state	state/keyring.go:40	constructed keyring signer	{"backend": "test", "path": "/Users/joshstein/.celestia-light-arabica-6/keys", "key name": "my_celes_key", "chain-id": "arabica-6"}
2023-05-30T16:36:17.726-0400	WARN	module/gateway	gateway/module.go:25	Gateway is enabled, however gateway endpoints are not authenticated. Use with caution!
2023-05-30T16:36:17.929-0400	INFO	badger	v2@v2.2007.4/levels.go:183	All 0 tables opened in 0s

2023-05-30T16:36:18.454-0400	INFO	module/header	header/config.go:58	No trusted peers in config, initializing with default bootstrappers as trusted peers
2023-05-30T16:36:18.459-0400	INFO	header/p2p	p2p/exchange.go:84	client: starting client	{"protocol ID": "/arabica-6/header-ex/v0.0.3"}
2023-05-30T16:36:18.459-0400	INFO	fraudserv	fraudserv/helpers.go:29	joining topic	{"id": "/arabica-6/fraud-sub/badencoding/v0.0.1"}
2023-05-30T16:36:18.459-0400	INFO	fraudserv	fraudserv/service.go:97	starting fraud proof service	{"protocol ID": "/arabica-6/fraud/v0.0.1"}
2023-05-30T16:36:19.007-0400	INFO	header/store	store/store.go:120	initialized head	"height": 1, "hash": "EE310062CBB13CE98CBC7EAD3F6A827F0E4A86043FDEB2DA42048821877FE45C"}
2023-05-30T16:36:19.008-0400	INFO	header/p2p	p2p/subscriber.go:40	joining topic	{"topic ID": "/arabica-6/header-sub/v0.0.1"}
2023-05-30T16:36:19.008-0400	INFO	header/sync	sync/sync_head.go:70	stored head header expired	{"height": 1}
2023-05-30T16:36:19.101-0400	INFO	header/sync	sync/sync_head.go:116	new network head	"height": 299119, "hash": "654C2CFA82C2DA1DDEAE74382598D8E90CDFDB1FC615ADF481BBC41B5AE135B8"}
2023-05-30T16:36:19.101-0400	WARN	header/sync	sync/sync_head.go:84	subjective initialization with an expired header	{"height": 299119}
2023-05-30T16:36:19.101-0400	WARN	header/sync	sync/sync_head.go:88	trusted peer is out of sync
2023-05-30T16:36:19.194-0400	WARN	header/sync	sync/sync_head.go:140	received known network header	{"current_height": 299119, "header_height": 299119, "header_hash": "654C2CFA82C2DA1DDEAE74382598D8E90CDFDB1FC615ADF481BBC41B5AE135B8"}
2023-05-30T16:36:19.194-0400	INFO	header/sync	sync/sync.go:200	syncing headers	{"from": 2, "to": 299119}
2023-05-30T16:36:19.195-0400	INFO	header/p2p	p2p/server.go:65	server: listening for inbound header requests	{"protocol ID": "/arabica-6/header-ex/v0.0.3"}
2023-05-30T16:36:19.196-0400	WARN	das	das/daser.go:92	checkpoint not found, initializing with height 1
2023-05-30T16:36:19.196-0400	INFO	das	das/daser.go:105	starting DASer from checkpoint: SampleFrom: 1, NetworkHead: 1
2023-05-30T16:36:19.196-0400	INFO	rpc	rpc/server.go:96	server started	{"listening on": "0.0.0.0:26658"}
2023-05-30T16:36:19.196-0400	INFO	gateway	gateway/server.go:51	server started	{"listening on": "127.0.0.1:26659"}
2023-05-30T16:36:19.196-0400	INFO	node	nodebuilder/node.go:110	

/_____/  /_____/  /_____/  /_____/  /_____/

Started celestia DA node
node type: 	light
network: 	arabica-6

/_____/  /_____/  /_____/  /_____/  /_____/

The p2p host is listening on:
*  /ip4/192.168.1.178/udp/2121/quic-v1/p2p/12D3KooWJ2DC39fbXLRGTFtCbUocY7dWpEB63kHLKckdEUYiKA8h
*  /ip6/::1/udp/2121/quic-v1/p2p/12D3KooWJ2DC39fbXLRGTFtCbUocY7dWpEB63kHLKckdEUYiKA8h
*  /ip4/192.168.1.178/tcp/2121/p2p/12D3KooWJ2DC39fbXLRGTFtCbUocY7dWpEB63kHLKckdEUYiKA8h
*  /ip6/::1/tcp/2121/p2p/12D3KooWJ2DC39fbXLRGTFtCbUocY7dWpEB63kHLKckdEUYiKA8h
*  /ip4/71.163.119.194/tcp/2121/p2p/12D3KooWJ2DC39fbXLRGTFtCbUocY7dWpEB63kHLKckdEUYiKA8h

panic: malformed hash: invalid namespaced hash length, got: 48, want: 90, codec:

goroutine 464 [running]:
github.com/celestiaorg/celestia-node/share/ipld.MustCidFromNamespacedSha256({0x1400317e4b0?, 0x0?, 0x0?})
	/Users/joshstein/celestia-node/share/ipld/nmt.go:159 +0xac
github.com/celestiaorg/celestia-node/share/ipld.Translate(0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/ipld/nmt.go:175 +0xac
github.com/celestiaorg/celestia-node/share/getters.(*IPLDGetter).GetShare(0x140007427c8, {0x105a45e60, 0x14008994230}, 0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/getters/ipld.go:54 +0x424
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetShare.func1({0x105a45e60?, 0x14008994230?}, {0x105a2f600?, 0x140007427c8?})
	/Users/joshstein/celestia-node/share/getters/cascade.go:45 +0x4c
github.com/celestiaorg/celestia-node/share/getters.cascadeGetters[...]({0x105a45f08, 0x1400253fad0}, {0x14001c4eae0, 0x2, 0x14001157750}, 0x14002575bd0?)
	/Users/joshstein/celestia-node/share/getters/cascade.go:123 +0x574
github.com/celestiaorg/celestia-node/share/getters.(*CascadeGetter).GetShare(0x14000742810, {0x105a45f08, 0x1400253fa40}, 0x14003112d70, 0x1, 0x0)
	/Users/joshstein/celestia-node/share/getters/cascade.go:48 +0x42c
github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).SharesAvailable.func1({0x14000763070?, 0x14008993fb0?})
	/Users/joshstein/celestia-node/share/availability/light/availability.go:65 +0x168
created by github.com/celestiaorg/celestia-node/share/availability/light.(*ShareAvailability).SharesAvailable
	/Users/joshstein/celestia-node/share/availability/light/availability.go:63 +0x29c
```

#### Version

```Shell
celestia version
Semantic version: v0.11.0-rc0
Commit: a438788f474f65aae3e33b3b8ee6db055f8d3607
Build Date: Tue May 30 16:33:21 EDT 2023
System version: arm64/darwin
Golang version: go1.20.2
```

**Comment by Wondertan** [comment]
Fixed by #2281
