### ISSUE TITLE
panic: Error creating blob: invalid size of the namespace id. got:10, want:29

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2321]
### Celestia Node version

v0.11.0-rc2

### OS

macOS

### Install tools

https://docs.celestia.org/nodes/celestia-node/ for Mac (Apple) x Arabica

### Steps to reproduce it

fund account:
```bash
celestia rpc state Balance
{
  "jsonrpc": "2.0",
  "result": {
    "denom": "utia",
    "amount": "100000000"
  },
  "id": 1
}
```

submit PFB with 10 byte namespace:
```bash
celestia rpc blob Submit 0x42690c204d39600fddd3 0xf1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f5
```

### Expected result

```bash
{
 “jsonrpc”: “2.0”,
 “result”: BLOCK_HEIGHT_OF_PFB,
 “id”: 1
}
```

### Actual result

panic: Error creating blob: invalid size of the namespace id. got:10, want:29

### Relevant log output

```Shell
celestia rpc blob Submit 0x42690c204d39600fddd3 0xf1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f5

panic: Error creating blob: invalid size of the namespace id. got:10, want:29

goroutine 1 [running]:
main.parseParams({0x16aea7822, 0x6}, {0x1400059c820, 0x2, 0x0?})
	/Users/joshstein/celestia-node/cmd/celestia/rpc.go:151 +0x1920
main.glob..func5(0x109348320?, {0x1400059c800?, 0x4?, 0x4?})
	/Users/joshstein/celestia-node/cmd/celestia/rpc.go:100 +0x70
github.com/spf13/cobra.(*Command).execute(0x109348320, {0x1400059c780, 0x4, 0x4})
	/Users/joshstein/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5ac
github.com/spf13/cobra.(*Command).ExecuteC(0x109348040)
	/Users/joshstein/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/joshstein/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/joshstein/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.run()
	/Users/joshstein/celestia-node/cmd/celestia/main.go:28 +0x58
main.main()
	/Users/joshstein/celestia-node/cmd/celestia/main.go:21 +0x1c
```

### Notes

Submitting with 8 byte namespace works, but 10 should also work.

I was editing the docs to show a 10 byte namespace in the RPC guide, but it did not work when I tested it out.

Before, 8 byte namespace:
`celestia rpc blob Submit 0x0c204d39600fddd3 0xf1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f5`

After (current), 10 byte namespace:
`celestia rpc blob Submit 0x42690c204d39600fddd3 0xf1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f5`

**Comment by SuperFluffy** [comment]
I am on `v0.11.0-rc2`. Using the `state.SubmitPayForBlob` returns a similar error from the endpoint but for 8 bytes:
```
---- state::submit_pay_for_blob_works stdout ----
thread 'state::submit_pay_for_blob_works' panicked at 'called `Result::unwrap()` on an `Err` value: RpcError { inner: Call(ErrorObject { code: ServerError(1), message: "unsupported namespace id length: id [115 104 114 100 115 117 101 113] must be 28 bytes but it was 8 bytes", data: None }) }', crates/astria-celestia-client/tests/it/state.rs:14:10
```

This is from the logs of the container running the celestia node bridge:

```
2023-06-06T13:51:44.489Z	WARN	rpc	go-jsonrpc@v0.1.9/handler.go:334	error in RPC call to 'state.SubmitPayForBlob': unsupported namespace id length: id [115 104 114 100 115 101 113 117] must be 28 bytes but it was 8 bytes
```

**Comment by distractedm1nd** [comment]
@SuperFluffy This is because celestia-app has changed the namespace size and is in the process of fully updating their docs. If you're using rust, here is the snippet I am currently using for namespaceID:

```rust
base64_serde_type!(pub(crate) Base64Standard, base64::engine::general_purpose::STANDARD);

pub struct NamespaceId(Vec<u8>);

impl NamespaceId {
    pub fn new_v0(hex: &str) -> Result<Self, hex::FromHexError> {
        let mut zero_padded_vec = vec![0; 21]; // 20 zero bytes
        zero_padded_vec.extend_from_slice(&hex::decode(hex)?);
        Ok(Self(zero_padded_vec))
    }
}

impl Serialize for NamespaceId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer,
    {
        Base64Standard::serialize(&self.0, serializer)
    }
}

impl<'de> Deserialize<'de> for NamespaceId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where
            D: Deserializer<'de>,
    {
        Ok(NamespaceId(Base64Standard::deserialize(deserializer)?))
    }
}


#[derive(Serialize, Deserialize)]
pub struct Blob {
    pub namespace: NamespaceId,
    #[serde(with = "Base64Standard")]
    pub data: Vec<u8>,
    pub share_version: u32,
    pub namespace_version: u32,
    #[serde(with = "Base64Standard")]
    pub commitment: Vec<u8>
}

impl Blob {
    pub fn new<T: Serialize>(namespace: NamespaceId, data: T) -> Result<Self, serde_json::error::Error> {
        let data = serde_json::to_string(&data)?;
        Ok(Self {
            namespace,
            data: data.into_bytes(),
            share_version: 0,
            namespace_version: 0,
            // TODO: add non-empty commitment once we have a way to compute it in rust
            commitment: vec![],
        })
    }
}
```

Also, I suggest moving to the blob module which is easier to use. Here is a jsonrpsee stub for the module in rust:
```rust
use jsonrpsee::proc_macros::rpc;
use jsonrpsee::core::{Error};
use crate::types::{Blob, NamespaceId};

//TODO: Add missing methods
#[rpc(client)]
pub trait BlobMod {
    #[method(name = "blob.Submit")]
    async fn submit_blobs(&self, blobs: Vec<Blob>) -> Result<u64, Error>;

    #[method(name = "blob.GetAll")]
    async fn get_all_blobs(&self, height: u64, namespaces: Vec<NamespaceId>) -> Result<Vec<Blob>, Error>;
}
```

It is missing the methods that retrieve the proofs and some other methods, but it should cover the bare minimum cases I hope. Please reach out to me if you need any help with your setup!
