### ISSUE TITLE
bug: panic in eds retriever

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2350]
found in TestFullReconstructFromLights

```
panic: runtime error: index out of range [43] with length 32

goroutine 414781 [running]:
github.com/celestiaorg/celestia-node/share/eds.(*retrievalSession).doRequest.func1.1(0x1401e690c98?, {0x1407fb1f6ff?, 0x1401e690c98?, 0x100f66108?})
	/Users/rford/Programming/Celestia/celestia-node/share/eds/retriever.go:269 +0x3a0
github.com/celestiaorg/celestia-node/share.GetShares.func1(0x10366c9a8?, {0x103685440?, 0x140aa9824c0?})
	/Users/rford/Programming/Celestia/celestia-node/share/get.go:40 +0x70
github.com/celestiaorg/celestia-node/share/ipld.GetLeaves.func1()
	/Users/rford/Programming/Celestia/celestia-node/share/ipld/get.go:144 +0x3b4
github.com/gammazero/workerpool.worker(0xd24c6d0?, 0xf?, 0x10100000000?)
	/Users/rford/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:237 +0x30
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
	/Users/rford/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:197 +0x220
```

**Comment by Wondertan** [comment]
This is very tricky. According to the logic, there should not be a case where we get the odd number 43.

**Comment by Wondertan** [comment]
It's likely to be a race condition somewhere. We couldn't run this swamp test with race flag because it exceeded the goroutine limit. Now that we don't have this limit, we should retest it with race and catch the bug. Actuallty there is an issue for that https://github.com/celestiaorg/celestia-node/issues/825

**Comment by renaynay** [comment]
Closing as likely fixed.
