### ISSUE TITLE
blob: (*Blob).UnmarshalJSON crashes with simple JSON []byte("{}")

### ISSUE THREAD

**Issue by odeke-em** [celestiaorg/celestia-node#3727]
### Celestia Node version

1a1286f454c1dd670af856153a8fc8674cd91192

### OS

darwin

### Steps to reproduce it

If you run this very simple repro
```go
package test

import (
     "testing"

     "github.com/celestiaorg/celestia-node/blob"
)

func TestBlobUnmarshalRepro(t *testing.T) {
     blob := new(blob.Blob)
     _ = blob.UnmarshalJSON([]byte("{}"))
}
```

### Expected result

No panic

### Actual result

```shell
$ go test -run=Repro
# github.com/celestiaorg/celestia-node/blob.test
--- FAIL: TestBlobUnmarshalRepro (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 12 [running]:
testing.tRunner.func1.2({0x10e8315c0, 0xc000065740})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1635 +0x35e
panic({0x10e8315c0?, 0xc000065740?})
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/runtime/panic.go:785 +0x132
github.com/celestiaorg/celestia-node/share.Namespace.Version(...)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/share/namespace.go:61
github.com/celestiaorg/celestia-node/blob.(*Blob).UnmarshalJSON(0xc0005b1f20, {0xc0004e8a98, 0x2, 0x2})
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/blob.go:172 +0x1c5
github.com/celestiaorg/celestia-node/blob_test.TestBlobUnmarshalRepro(0xc0004116c0?)
	/Users/emmanuelodeke/go/src/github.com/celestiaorg/celestia-node/blob/repro_test.go:11 +0x4c
testing.tRunner(0xc0004116c0, 0x10e975e50)
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/Users/emmanuelodeke/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-amd64/src/testing/testing.go:1743 +0x390
exit status 2
FAIL	github.com/celestiaorg/celestia-node/blob	1.501s
```

### Notes

To fix it, please check that the namespace is non-empty

```diff
diff --git a/blob/blob.go b/blob/blob.go
index 369d464e..3b26e5f1 100644
--- a/blob/blob.go
+++ b/blob/blob.go
@@ -168,6 +168,10 @@ func (b *Blob) UnmarshalJSON(data []byte) error {
 		return err
 	}
 
+	if len(jsonBlob.Namespace) == 0 {
+		return errors.New("expected a non-empty namespace")
+	}
+
 	b.Blob = &blob.Blob{}
 	b.Blob.NamespaceVersion = uint32(jsonBlob.Namespace.Version())
 	b.Blob.NamespaceId = jsonBlob.Namespace.ID()
```

**Comment by odeke-em** [comment]
I have mailed out a PR with the fixes along with the fuzzers per https://github.com/celestiaorg/celestia-node/pull/3732
