### ISSUE TITLE
Panic error when starting new node celestia-node:v0.16.2-mocha

### ISSUE THREAD

**Issue by breezytm** [celestiaorg/celestia-node#3819]
### Summary of Bug

Starting a node using the latest `celestia-node:v0.16.2-mocha` throws the following error when syncing a node from genesis. The issue does not seem to exist in `v0.16.0`

```
2024-10-05T23:34:12.954Z	WARN	rpc	rpc/flags.go:56	RPC authentication is disabled
2024-10-05T23:34:12.961Z	INFO	node	nodebuilder/module.go:27	Accessing keyring...
2024-10-05T23:34:12.961Z	WARN	module/p2p	p2p/config.go:90	routingTableRefreshPeriod is not valid. restoring to default value: 60000000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23e972e]

goroutine 1 [running]:
github.com/celestiaorg/celestia-node/share/p2p/discovery.(*Parameters).Validate(0x2487a00?)
t	/src/share/p2p/discovery/options.go:43 +0xe
github.com/celestiaorg/celestia-node/nodebuilder/share.(*Config).Validate(0xc000dbc458, 0xd0?)
	/src/nodebuilder/share/config.go:57 +0xe5
github.com/celestiaorg/celestia-node/nodebuilder/share.ConstructModule(0x3, 0xc000dbc458, {0x0, 0x0, 0x0})
	/src/nodebuilder/share/module.go:26 +0x50
github.com/celestiaorg/celestia-node/nodebuilder.ConstructModule(0x3, {0x2c098e6, 0x7}, 0xc000dbc308, {0x3884078, 0xc0018c0380})
	/src/nodebuilder/module.go:50 +0x7d1
github.com/celestiaorg/celestia-node/nodebuilder.NewWithConfig(0xe?, {0x2c098e6?, 0x5224fc0?}, {0x3884078?, 0xc0018c0380?}, 0x2c13047?, {0xc0009e1b78, 0x0, 0x4?})
	/src/nodebuilder/node.go:100 +0x4b
github.com/celestiaorg/celestia-node/cmd.Start.func1(0xc000d72f08, {0xc000afc240?, 0x4?, 0x2c04d64?})
	/src/cmd/start.go:54 +0x471
github.com/spf13/cobra.(*Command).execute(0xc000d72f08, {0xc000afc180, 0xc, 0xc})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x51c4b00)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
main.run()
	/src/cmd/celestia/main.go:48 +0x4f
main.main()
	/src/cmd/celestia/main.go:41 +0x13
```

### Version

Docker Image: `celestia-node:v0.16.2-mocha`

### Steps to Reproduce

Deploy a new node using the following steps

```
celestia full init --p2p.network mocha
celestia full start --core.ip https://{endpoint uri} 
```

**Comment by breezytm** [comment]
Correction: It seems like version `v0.16.0` works for `mocha` network but does not work for `celestia`

**Comment by renaynay** [comment]
@breezytm There was a break to the config in v0.15.0, please follow config re-initialisation steps in the documentation at https://docs.celestia.org/ and try re-running.
