### ISSUE TITLE
flaky TestBridge_WithMockedCoreClient

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#608]
### Steps to reproduce it

CI

### Expected result

not flaky

### Actual result

flaky

### Relevant log output

```shell
--- SKIP: TestBridge_WithMockedCoreClient (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb21c80]

goroutine 1282 [running]:
github.com/tendermint/tendermint/libs/pubsub.(*Subscription).Out(0x2)
	/home/runner/go/pkg/mod/github.com/celestiaorg/celestia-core@v0.34.14-celestia.0.20220228062426-721562a3544d/libs/pubsub/subscription.go:43
github.com/tendermint/tendermint/rpc/core.Subscribe.func1()
	/home/runner/go/pkg/mod/github.com/celestiaorg/celestia-core@v0.34.14-celestia.0.20220228062426-721562a3544d/rpc/core/events.go:50 +0x9e
created by github.com/tendermint/tendermint/rpc/core.Subscribe
	/home/runner/go/pkg/mod/github.com/celestiaorg/celestia-core@v0.34.14-celestia.0.20220228062426-721562a3544d/rpc/core/events.go:47 +0x485
FAIL	github.com/celestiaorg/celestia-node/node	0.193s
FAIL
exit status 1
```
https://github.com/celestiaorg/celestia-node/runs/5958778931?check_suite_focus=true#step:4:406

**Comment by Wondertan** [comment]
@liamsi, @adlerjohn

Consult https://github.com/celestiaorg/celestia-core/issues/667 for why this happens

**Comment by liamsi** [comment]
I know, just keeping track of the flaky tests makes still sense. Otherwise someone seeing a test failure won't know if the team is aware or not.
