### ISSUE TITLE
Panic Trigger When Retrieving namespaced_shares of specific block height

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/celestia-node#703]
### Celestia Node version

renaynay:rpc-endpoints-refactor branch

### OS

Ubuntu Linux 20.04 (LTS) x64 instance machine

### Install tools

makefiles

### Steps to reproduce it

I am using a single-node.sh custom script:
```
#!/bin/sh

set -o errexit -o nounset

CHAINID="devnet-2"
app="./celestia-appd"

# Build genesis file incl account for passed address
coins="1000000000000000uceles"
$app init $CHAINID --chain-id $CHAINID 
$app keys add validator --keyring-backend="test"
$app keys add celes --keyring-backend="test"
# this won't work because the some proto types are decalared twice and the logs output to stdout (dependency hell involving iavl)
$app add-genesis-account $($app keys show validator -a --keyring-backend="test") $coins
$app add-genesis-account $($app keys show celes -a --keyring-backend="test") $coins
$app gentx validator 5000000000uceles --keyring-backend="test" --chain-id $CHAINID
$app collect-gentxs

# Set proper defaults and change ports
sed 's#"tcp://127.0.0.1:26657"#"tcp://0.0.0.0:26657"#g' ~/.celestia-app/config/config.toml
sed 's/timeout_commit = "5s"/timeout_commit = "1s"/g' ~/.celestia-app/config/config.toml
sed 's/timeout_propose = "3s"/timeout_propose = "1s"/g' ~/.celestia-app/config/config.toml
sed 's/index_all_keys = false/index_all_keys = true/g' ~/.celestia-app/config/config.toml

# Start the celestia-app
$app start --grpc.enable
```

I am also running a Celestia Light Node connected to this Celestia App instance sharing the same keys generated by the above script.

I generate a namespace_id and data hexadecimal using this playground: https://go.dev/play/p/ZZWYSSHTRdo

I then get the following values that I submit to `submit_pfd`:
```sh
curl -X POST -d '{"namespace_id": "0c204d39600fddd3", "data": "f1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f56f", "gas_limit": 100000}' http://127.0.0.1:26658/submit_pfd
```

It confirms the transaction with this output:
```
{"height":11977,"txhash":"5CF14DBA3419D1685879B2471AD1191156779CAAB6F851B80E1869C9B9AAC473","data":"0A180A162F7061796D656E742E4D7367506179466F7244617461","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"/payment.MsgPayForData\"}]},{\"type\":\"payfordata\",\"attributes\":[{\"key\":\"signer\",\"value\":\"celes1vdjkcetnx958ymrgvuergdtxxe58j6n4x5mhsarrx3cnqmf5wcu8xut4vdhrqdts89enyvq5ghg33\"},{\"key\":\"size\",\"value\":\"256\"}]}]}]","logs":[{"events":[{"type":"message","attributes":[{"key":"action","value":"/payment.MsgPayForData"}]},{"type":"payfordata","attributes":[{"key":"signer","value":"celes1vdjkcetnx958ymrgvuergdtxxe58j6n4x5mhsarrx3cnqmf5wcu8xut4vdhrqdts89enyvq5ghg33"},{"key":"size","value":"256"}]}]}],"gas_wanted":100000,"gas_used":38546}
```

I then try to retrieve it using `namespaced_shares` endpoint:
```
curl -X GET http://127.0.0.1:26658/namespaced_shares/f1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f56f/height/11977
```
This output is returned:
```
curl: (52) Empty reply from server
```

The Celestia Light Node logs show the following:
```
2022-05-12T09:34:26.657Z        INFO    das     das/daser.go:153        sampling successful {
"height": 998494, "hash": "52B682735944325183C1174BDEA60E38208C92FC4099D9CBEE4CCD8EB1841708",
 "square width": 2, "finished (s)": 0.000409222}
2022/05/12 09:34:35 http: panic serving 127.0.0.1:33074: runtime error: slice bounds out of r
ange [:56] with capacity 48
goroutine 3731994 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x1a7f480, 0xc0166435c0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/celestiaorg/nmt.MaxNamespace(...)
        /root/go/pkg/mod/github.com/celestiaorg/nmt@v0.8.0/nmt.go:385
github.com/celestiaorg/celestia-node/service/share.(*service).GetSharesByNamespace(0xc00143b9
80, {0x2101c80, 0xc013da8540}, 0xc01204d720, {0xc00d24a100, 0x0, 0x0})
        /root/celestia-node/service/share/share.go:152 +0x7b5
github.com/celestiaorg/celestia-node/service/rpc.(*Handler).handleSharesByNamespaceRequest(0x
c000060d60, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508800)
        /root/celestia-node/service/rpc/share.go:64 +0x236
net/http.HandlerFunc.ServeHTTP(0x1882500, {0x20dfbe8, 0xc00d50c2a0}, 0xc)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/celestiaorg/celestia-node/service/rpc.setContentType.func1({0x20dfbe8, 0xc00d50c2a
0}, 0xc013da8540)
        /root/celestia-node/service/rpc/server.go:40 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc00d508700, {0x20dfbe8, 0xc00d50c2a0}, 0x4773ae)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00003a3c0, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508
600)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/celestiaorg/celestia-node/service/rpc.(*Server).ServeHTTP(0x0, {0x20dfbe8, 0xc00d5
0c2a0}, 0x46a96e)
        /root/celestia-node/service/rpc/server.go:80 +0x27
net/http.serverHandler.ServeHTTP({0xc013da81b0}, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508600)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0128aa6e0, {0x2101c80, 0xc007583080})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
```

### Expected result

I should be able to retrieve the `namespaced_shares` data after requesting the namespace_id at that specific block height I specified.

### Actual result

Log output shows:

```
2022-05-12T09:34:26.657Z        INFO    das     das/daser.go:153        sampling successful {
"height": 998494, "hash": "52B682735944325183C1174BDEA60E38208C92FC4099D9CBEE4CCD8EB1841708",
 "square width": 2, "finished (s)": 0.000409222}
2022/05/12 09:34:35 http: panic serving 127.0.0.1:33074: runtime error: slice bounds out of r
ange [:56] with capacity 48
goroutine 3731994 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x1a7f480, 0xc0166435c0})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/celestiaorg/nmt.MaxNamespace(...)
        /root/go/pkg/mod/github.com/celestiaorg/nmt@v0.8.0/nmt.go:385
github.com/celestiaorg/celestia-node/service/share.(*service).GetSharesByNamespace(0xc00143b9
80, {0x2101c80, 0xc013da8540}, 0xc01204d720, {0xc00d24a100, 0x0, 0x0})
        /root/celestia-node/service/share/share.go:152 +0x7b5
github.com/celestiaorg/celestia-node/service/rpc.(*Handler).handleSharesByNamespaceRequest(0x
c000060d60, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508800)
        /root/celestia-node/service/rpc/share.go:64 +0x236
net/http.HandlerFunc.ServeHTTP(0x1882500, {0x20dfbe8, 0xc00d50c2a0}, 0xc)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/celestiaorg/celestia-node/service/rpc.setContentType.func1({0x20dfbe8, 0xc00d50c2a
0}, 0xc013da8540)
        /root/celestia-node/service/rpc/server.go:40 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc00d508700, {0x20dfbe8, 0xc00d50c2a0}, 0x4773ae)
        /usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00003a3c0, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508
600)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/celestiaorg/celestia-node/service/rpc.(*Server).ServeHTTP(0x0, {0x20dfbe8, 0xc00d5
0c2a0}, 0x46a96e)
        /root/celestia-node/service/rpc/server.go:80 +0x27
net/http.serverHandler.ServeHTTP({0xc013da81b0}, {0x20dfbe8, 0xc00d50c2a0}, 0xc00d508600)
        /usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0128aa6e0, {0x2101c80, 0xc007583080})
        /usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3033 +0x4e8
```

**Comment by YazzyYaz** [comment]
Ah! I see, I should've been calling my `namespace_id` instead of the `data`. Sorry, complete miss on my part.

**Comment by renaynay** [comment]
No worries, but I should implement a check.

**Comment by liamsi** [comment]
Good catch Yaz. Users shouldn't be able to take down the RPC server or node by sending it invalid inputs.

**Comment by renaynay** [comment]
This doesn't actually take down the node, btw.

**Comment by liamsi** [comment]
But the rpc server? Ot just that one go-rountine?

**Comment by renaynay** [comment]
One go routine

**Comment by Wondertan** [comment]
Yeah, because of `recover()`. Some OSS Go HTTP servers/frameworks also send 5xx errors to the user automatically on recovered panics, unlike the native one.
