### ISSUE TITLE
tests: panic in PubSub

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#899]
```
2022-07-06T11:49:46.3152764Z panic: send on closed channel
2022-07-06T11:49:46.3152919Z 	panic: close of closed channel
2022-07-06T11:49:46.3152935Z 
2022-07-06T11:49:46.3153068Z goroutine 56370 [running]:
2022-07-06T11:49:46.3153412Z github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop.func1()
2022-07-06T11:49:46.3153919Z 	/home/runner/go/pkg/mod/github.com/celestiaorg/go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/pubsub.go:535 +0x74
2022-07-06T11:49:46.3154058Z panic({0x1e3ad40, 0x2dadb30})
2022-07-06T11:49:46.3154306Z 	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207
2022-07-06T11:49:46.3154781Z github.com/libp2p/go-libp2p-pubsub.(*PubSub).announce(0xc009cc9000, {0x2170a15, 0xa}, 0x0)
2022-07-06T11:49:46.3155353Z 	/home/runner/go/pkg/mod/github.com/celestiaorg/go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/pubsub.go:889 +0x21f
2022-07-06T11:49:46.3155800Z github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleRemoveSubscription(0xc009cc9000, 0xc00a0d2e60)
2022-07-06T11:49:46.3156313Z 	/home/runner/go/pkg/mod/github.com/celestiaorg/go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/pubsub.go:787 +0x12a
2022-07-06T11:49:46.3156728Z github.com/libp2p/go-libp2p-pubsub.(*PubSub).processLoop(0xc009cc9000, {0x2dcd790, 0xc004d00280})
2022-07-06T11:49:46.3157237Z 	/home/runner/go/pkg/mod/github.com/celestiaorg/go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/pubsub.go:583 +0xa25
2022-07-06T11:49:46.3157639Z created by github.com/libp2p/go-libp2p-pubsub.NewPubSub
2022-07-06T11:49:46.3158106Z 	/home/runner/go/pkg/mod/github.com/celestiaorg/go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/pubsub.go:323 +0xdea
2022-07-06T11:49:46.3158402Z FAIL	github.com/celestiaorg/celestia-node/node/tests	111.074s
```

Note that [this](https://github.com/celestiaorg/celestia-node/pull/887) existing pubsub update PR would fix the issue. The bug is fixed downstream. The question is then, should we rely on the untagged pubsub commit in main, while having the issue fixed, or should we wait until the proper tag and live with this bug which is very likely to happen not only in tests. I am inclined towards the first option.

**Comment by Bidon15** [comment]
Ref: https://github.com/celestiaorg/celestia-node/pull/887
