### ISSUE TITLE
Crash during syncing full storage node

### ISSUE THREAD

**Issue by Vanish-Gold** [celestiaorg/celestia-node#952]
### Celestia Node version

v0.3.0-rc2

### OS

Ubuntu 20.04.4

### Install tools

I used screen. At 1 working validator node well. At 2 im trying to sync full storge node. I think it has no effect.

### Steps to reproduce it

celestia full start --core.grpc https://celestia-testnet-rpc.polkachu.com/:9090 --keyring.accname Vanish   (at other RPC Endpoints it killing process after aroung 3k blocks)

### Expected result

full sync)

### Actual result

![unknown](https://user-images.githubusercontent.com/109694278/181365901-409bb93d-618c-4d3b-8c21-09f8893d56f2.png)

### Relevant log output

```shell
goroutine 431031371 [running]:

github. com/celestiaorg/nmt. (*Hasher) .HashNode (0xc05590d530, {0xc09ba8c3cl, 0x30, Ox3f}, {OxcO9ba8c3f1, 0x6, Oxf}) /root/go/pkg/mod/github.com/celestiaorg/nmt@v0.10.0/hasher.go:122 +0x545
github. com/celestiaorg/celestia-node/ipld/plugin. (*namespaceHasher) .Sum(0xc05590d560, {0xc000118b10, 0x7701, Oxc0bc2a2b98}) /root/celestia-node/ipld/plugin/nmt.go:69 +0x8f
github. com/multiformats/go-multihash.encodeHash ({0x2c48838, 0xc05590d560}, 0x7701, 0x30) 
/root/go/pkg/mod/ github. com/multiformats/go-multihash@v0.2.0/sum.go:54 +0x42

github. com/multiformats/go-multihash.Sum{{0xc09ba8c3c0, 0x37, 0x40}, Ox1?, 0x7701?)
/root/go/pkg/mod/ github. com/multiformats/go-multihash@v0.2.0/sum.go:30 +0x90
github.com/ipfs/go-cid. Prefix.Sum({{0xc0al70f£018?, 0x8?, 0x8?, 0xc0263e2900?7}, {Oxc09ba8c3c0?, Oxc0bc2a2c80?, 0x4850257}) /root/go/pkg/mod/github.com/ipfs/go-cid@v0.2.0/cid.go:532 +0xa5S
github. com/ipfs/go-bitswap/message.newMessageFromProto({{{0x0, 0x0, 0x0}, Ox0}, {0x0, 0x0, 0x0}, {0xc0263e2900, 0x2, 0x2}, ...}) /root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/message/message.go:222 +0xlbb
github. com/ipfs/go-bitswap/message. FromMsgReader ({0x7£45908857d8, 0xc02a282480}) /root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/message/message.go:416 +0x118
github. com/ipfs/go-bitswap/network. (*impl) .handleNewStream(0xc0012bcd20, {0x2c57888?, Oxc05cb8c200})
/root/go/pkg/mod/github.com/ipfs/go-bitswap@v0.7.0/network/ipfs_impl.go:413 +0x39c 
github. com/libp2p/go-libp2p/p2p/host/basic. (*BasicHost) .SetStreamHandler.funcl {{0xc014b2£350, 0x23}, {0x7£4590bb6e98?, Oxc05cb8c200}) /root/go/pkg/mod/github.com/libp2p/go-libp2p@v0.20.2/p2p/host/basic/basic_host.go:568 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic. (*BasicHost) .newStreamHandler /root/go/pkg/mod/github . com/1ibp2p/go-1ibp2pev0 . 20. 2/p2p/host/basic/basic_host.go:411 +0x715
```

**Comment by Wondertan** [comment]
Ok, thanks for this bug "pull up"😁 @Vanish-Gold Capybara. It seems like there is a bug somewhere, as short mitigation way, does the restart help, or do you see this issue being reproduced constantly?

**Comment by Wondertan** [comment]
Seems very similar to https://github.com/celestiaorg/celestia-node/issues/780

**Comment by Vanish-Gold** [comment]
>

**Comment by Vanish-Gold** [comment]
After restarting it works

**Comment by Vanish-Gold** [comment]
But i don't know where the bug is from

**Comment by renaynay** [comment]
Thank you for opening this issue @Vanish-Gold, we will look into it 👍🏻
