### ISSUE TITLE
node/tests: panic during sync(happens only in tests)

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#955]
```
2022-07-28T12:30:02.372+0200    INFO    header/store    store/store.go:305      new head        {"height": 27, "hash": "073FF6576520D81ED0BC24DD3A195DD23F4943A7787EAC4EA865780D01576488"}
2022-07-28T12:30:02.303+0200    WARN    pubsub  go-libp2p-pubsub@v0.6.2-0.20220628100036-657948473f1f/tag_tracer.go:157 error bumping delivery tag: no decaying tag registered for topic header-sub
panic: 2022-07-28T12:30:02.372+0200     DEBUG   basichost       basic/basic_host.go:409 protocol negotiation took 1.109829ms
runtime error: slice bounds out of range [:2] with capacity 1

goroutine 144813 [running]:
github.com/celestiaorg/celestia-node/header/sync.(*headerRange).Before(0x326f869?, 0x2f14598?)
        /home/Wondertan/src/go/celestia-node/header/sync/ranges.go:147 +0x186
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).findHeaders(0xc0091ffe60, {0x2f14598, 0xc012e7b100}, 0x17, 0x18)
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:346 +0x269
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).processHeaders(0xc0091ffe60, {0x2f14598, 0xc012e7b100}, 0xc02d97dd08?, 0x91ffae?)
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:308 +0x28
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).doSync(0xc0091ffe60, {0x2f14598, 0xc012e7b100}, 0xc01d464000, 0xc02b518900)
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:293 +0x186
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).syncTo(0xc0091ffe60, {0x2f14598, 0xc012e7b100}, 0xc02b518900)
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:259 +0x23e
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).sync(0xc02d97df88?, {0x2f14598, 0xc012e7b100})
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:179 +0xdb
github.com/celestiaorg/celestia-node/header/sync.(*Syncer).syncLoop(0xc0091ffe60, {0x2f14598, 0xc012e7b100})
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:164 +0x45
created by github.com/celestiaorg/celestia-node/header/sync.(*Syncer).Start
        /home/Wondertan/src/go/celestia-node/header/sync/sync.go:67 +0x105
FAIL    github.com/celestiaorg/celestia-node/node/tests 38.952s
FAIL
make: *** [Makefile:89: test-swamp] Error 1

```

**Comment by rootulp** [comment]
I observed a similar panic when I ran `make test` locally after rebasing a PR that isn't related to the header/store

```error
2023-01-26T15:37:56.592-0500	ERROR	header/sync	sync/sync.go:201	syncing headers	{"from": 34, "to": 37, "err": "header/store: non-adjacent: head 35, attempted 35"}
2023-01-26T15:37:56.592-0500	ERROR	header/sync	sync/sync.go:201	syncing headers	{"from": 31, "to": 37, "err": "header/store: non-adjacent: head 33, attempted 32"}
2023-01-26T15:37:56.607-0500	ERROR	header/sync	sync/sync.go:201	syncing headers	{"from": 31, "to": 37, "err": "header/store: non-adjacent: head 32, attempted 32"}
panic: runtime error: slice bounds out of range [:2] with capacity 1

goroutine 163777 [running]:
github.com/celestiaorg/celestia-node/libs/header/sync.(*headerRange[...]).Before(0x14035189c00, 0x25)
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/ranges.go:150 +0x184
github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).findHeaders(0x1401bb21ce0, {0x105c3a480, 0x14006d45f40}, 0x1d, 0x25)
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:278 +0x1fc
github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).processHeaders(0x1401bb21ce0?, {0x105c3a480, 0x14006d45f40}, 0x14061d2ed28, 0x1045f8b44?)
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:244 +0x2c
github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).doSync(0x1401bb21ce0, {0x105c3a480, 0x14006d45f40}, 0x0, 0x0?)
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:228 +0x1b0
github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).sync(0x1401bb21ce0, {0x105c3a480, 0x14006d45f40})
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:194 +0x230
github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).syncLoop(0x1401bb21ce0)
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:162 +0x3c
created by github.com/celestiaorg/celestia-node/libs/header/sync.(*Syncer[...]).Start
	/Users/rootulp/git/rootulp/celestia/celestia-node/libs/header/sync/sync.go:95 +0x174
FAIL	github.com/celestiaorg/celestia-node/nodebuilder/tests	45.667s
```
