### ISSUE TITLE
test: flakiness FillBlocks

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#985]
```
--- PASS: TestFullReconstructFromBridge (1.16s)
=== RUN   TestFullReconstructFromLights
panic: Fail in goroutine after TestFullReconstructFromBridge has completed
goroutine 19355 [running]:
testing.(*common).Fail(0xc003b189c0)
       /opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:817 +0xe5
testing.(*common).Errorf(0xc003b189c0, {0x22898b1?, 0xc003b189c0?}, {0xc0089bb800?, 0x47822f?, 0xc002c28f90?})
	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:934 +0x65
github.com/stretchr/testify/assert.Fail({0x2f1f3a0, 0xc003b189c0}, {0xc0040c4120, 0x84}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:264 +0x384
github.com/stretchr/testify/assert.NoError({0x2f1f3a0, 0xc003b189c0}, {0x2f1f0c0, 0xc004f7b290}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.0/assert/assertions.go:1392 +0x105
github.com/stretchr/testify/require.NoError({0x2f27150, 0xc003b189c0}, {0x2f1f0c0, 0xc004f7b290}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.0/require/require.go:1261 +0x96
github.com/celestiaorg/celestia-node/node/tests/swamp.(*Swamp).SubmitData(0xc003d57830, {0x2f3b2a0, 0xc004baaa80}, 0x0?, {0xc004393000, 0x1000, 0x100c000ed7d38?})
	/home/runner/work/celestia-node/celestia-node/node/tests/swamp/swamp_tx.go:19 +0x105
github.com/celestiaorg/celestia-node/node/tests/swamp.(*Swamp).FillBlocks(0xc003d57830, {0x2f3b2a0, 0xc004baaa80}, 0xc004022e40?, 0x10, 0x14)
	/home/runner/work/celestia-node/celestia-node/node/tests/swamp/swamp_tx.go:31 +0x177
created by github.com/celestiaorg/celestia-node/node/tests.TestFullReconstructFromBridge
	/home/runner/work/celestia-node/celestia-node/node/tests/reconstruct_test.go:47 +0x14b
FAIL	github.com/celestiaorg/celestia-node/node/tests	17.078s
FAIL
```

**Comment by vgonkivs** [comment]
The root cause is that `FillBlocks` contains `require` statements which  is called in a separate goroutine.
